- name: Install Python Libraries
  apt:
    name:
      - python
      - python-pip
      - python-dev
      - python-virtualenv
      - python-setuptools
      - python3-pip
      - python3-dev
      - python3-virtualenv
      - python3-setuptools
      - libffi-dev
      - libssl-dev
      - libjpeg-dev
      - zlib1g-dev
      - swig