- name: Install tcpdump
  apt:
    name:
      - tcpdump
      - apparmor-utils

- name: Disable AppArmor for tcpdump
  shell: aa-disable /usr/sbin/tcpdump 2& > /dev/null

- name: Add group pcap
  group:
    name: pcap

- name: Change tcpdump group owner
  file:
    path: /usr/sbin/tcpdump
    group: pcap

- name: Change capabilities of tcpdump
  capabilities:
    path: /usr/sbin/tcpdump
    capability: cap_net_raw,cap_net_admin=eip