---
- name: Set fact pip_url HEAD
  set_fact:
    pip_url: https://github.com/volatilityfoundation/volatility/archive/master.tar.gz

- name: ensure virtualenv is present
  package:
    name: python-virtualenv
    state: present
  register: pkg_result
  until: pkg_result is success
- name: install volatility pip dependencies - virtualenv
  pip:
    name: 
      - setuptools
      - pip
      - pycrypto
      - distorm3
    state: present
    virtualenv: /usr/local/env-volatility
  register: pkg_result
  until: pkg_result is success

- name: install volatility - virtualenv
  pip:
    name: https://github.com/volatilityfoundation/volatility/archive/master.tar.gz
    state: present
    virtualenv: /usr/local/env-volatility
  register: pkg_result
  until: pkg_result is success

- name: symlink volatility in usual path
  file:
    src: "/usr/local/env-volatility/bin/vol.py"
    dest: "/usr/local/bin/vol.py"
    state: link

- name: ensure git is present
  package: name=git state=present
  register: pkg_result
  until: pkg_result is success

- name: Volatility profiles
  git:
    repo: https://github.com/volatilityfoundation/profiles.git
    dest: "/usr/local/share/volatility/profiles"
    version: "{{ volatility_profiles_version | default('524a5340bbf48f4a6f48d344d2554fdf65f6c1d4') }}"